# Certificate Issuer for Let's Encrypt SSL
# Requires cert-manager to be installed
#
# Install cert-manager:
# kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.0/cert-manager.yaml

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # ACME server URL for Let's Encrypt production
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email for Let's Encrypt notifications
    email: your-email@example.com  # CHANGE THIS
    # Secret to store ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # HTTP-01 challenge solver
    solvers:
    - http01:
        ingress:
          class: nginx

---
# Staging issuer for testing (optional)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # ACME server URL for Let's Encrypt staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: your-email@example.com  # CHANGE THIS
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx

