# Frontend service (local with NodePort)

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: pids-local
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pids-local
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: pids-app:frontend-local
        imagePullPolicy: Never  # Use local image, don't try to pull
        ports:
        - containerPort: 80
          name: http
        env:
        - name: NODE_ENV
          value: development
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "250m"

