name: pids-app
services:
- name: pids-frontend
  image:
    registry_type: DOCR
    repository: fidl-containers/pids-frontend
    tag: main
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 80
  routes:
  - path: /
  health_check:
    http_path: /health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production

- name: pids-backend
  image:
    registry_type: DOCR
    repository: fidl-containers/pids-backend
    tag: main
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /api
  health_check:
    http_path: /api/health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: MONGODB_URI
    value: mongodb://localhost:27017/pids
  - key: MINIO_ENDPOINT
    value: localhost:9000
  - key: MINIO_ACCESS_KEY
    value: minioadmin
  - key: MINIO_SECRET_KEY
    value: minioadmin
  - key: KEYCLOAK_URL
    value: http://localhost:8080
  - key: KEYCLOAK_REALM
    value: pids
  - key: KEYCLOAK_CLIENT_ID
    value: pids-frontend