name: pids-app
services:
- name: pids-frontend
  image:
    registry_type: DOCR
    repository: fidl-containers/pids-frontend
    tag: main
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 80
  routes:
  - path: /
  health_check:
    http_path: /health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production

- name: pids-api
  image:
    registry_type: DOCR
    repository: fidl-containers/pids-api
    tag: main
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /api
  health_check:
    http_path: /api/health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: MONGODB_URI
    value: mongodb://mongodb:27017/pids
  - key: MINIO_ENDPOINT
    value: minio:9000
  - key: MINIO_ACCESS_KEY
    value: minioadmin
  - key: MINIO_SECRET_KEY
    value: minioadmin
  - key: KEYCLOAK_URL
    value: http://keycloak:8080
  - key: KEYCLOAK_REALM
    value: pids
  - key: KEYCLOAK_CLIENT_ID
    value: pids-frontend

- name: mongodb
  image:
    registry_type: DOCR
    repository: mongo
    tag: "7"
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 27017
  envs:
  - key: MONGO_INITDB_DATABASE
    value: pids

- name: minio
  image:
    registry_type: DOCR
    repository: minio/minio
    tag: latest
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 9000
  envs:
  - key: MINIO_ROOT_USER
    value: minioadmin
  - key: MINIO_ROOT_PASSWORD
    value: minioadmin
  run_command: server /data --console-address ":9001"

- name: keycloak
  image:
    registry_type: DOCR
    repository: quay.io/keycloak/keycloak
    tag: latest
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  envs:
  - key: KEYCLOAK_ADMIN
    value: admin
  - key: KEYCLOAK_ADMIN_PASSWORD
    value: admin
  - key: KC_DB
    value: postgres
  - key: KC_DB_URL
    value: jdbc:postgresql://keycloak-db:5432/keycloak
  - key: KC_DB_USERNAME
    value: keycloak
  - key: KC_DB_PASSWORD
    value: keycloak
  run_command: start-dev

- name: keycloak-db
  image:
    registry_type: DOCR
    repository: postgres
    tag: "15"
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5432
  envs:
  - key: POSTGRES_DB
    value: keycloak
  - key: POSTGRES_USER
    value: keycloak
  - key: POSTGRES_PASSWORD
    value: keycloak
