---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: pids-production
  labels:
    app: keycloak
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: keycloak
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: pids-production
  labels:
    app: keycloak
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:latest
        args:
        - start
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: admin-password
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL
          value: jdbc:postgresql://keycloak-db:5432/keycloak
        - name: KC_DB_USERNAME
          value: keycloak
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: QUARKUS_SMALLRYE_HEALTH_ROOT_PATH
          value: "/health"
        - name: KC_METRICS_ENABLED
          value: "true"
        - name: KC_PROXY
          value: edge
        - name: KC_PROXY_HEADERS
          value: forwarded
        - name: KC_HOSTNAME_STRICT
          value: "false"
        # External hostname and path so Keycloak generates correct URLs behind proxy
        - name: KC_HOSTNAME
          value: https://toads.directory
        - name: KC_HOSTNAME_PATH
          value: /auth
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HTTP_RELATIVE_PATH
          value: /auth
        - name: KC_HTTP_MANAGEMENT_PORT
          value: "9000"
        # Disable clustering for simpler deployment
        # Clustering can cause issues with just 2 replicas if one pod crashes
        - name: KC_CACHE
          value: local
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 5

